#pragma once

/*
 * Runtime interface switches. Keep these at 1 while using the existing
 * serial dashboard and OLED. Set either to 0 for a control-loop build where
 * J-Link is the only live tuning/observation path.
 */
#ifndef RA4M2_ENABLE_UART_DASHBOARD
#define RA4M2_ENABLE_UART_DASHBOARD 1
#endif

#ifndef RA4M2_ENABLE_OLED_DISPLAY
#define RA4M2_ENABLE_OLED_DISPLAY 1
#endif

#ifndef RA4M2_ENABLE_JLINK_TUNING
#define RA4M2_ENABLE_JLINK_TUNING 1
#endif

#ifndef RA4M2_USE_SVPWM
#define RA4M2_USE_SVPWM 1
#endif

#ifdef __cplusplus
extern "C" {
#endif
#include "hal_data.h"
#ifdef __cplusplus
}
#endif

/*
 * Logical pin IDs used by the SimpleFOC driver constructors.
 *
 * The real pin/peripheral routing remains the one generated by FSP:
 *   A group: g_three_phase_pwm0 -> GPT0/GPT1/GPT2 -> PWMA_1/2/3
 *            P108/P104/P102 in the current configuration.xml.
 *   B group: optional legacy mapping, not generated by the current FSP config.
 */
enum RenesasSimpleFOCPin
{
    RA_PWM_A_U = 10000,
    RA_PWM_A_V = 10001,
    RA_PWM_A_W = 10002,
    RA_PWM_B_U = 10010,
    RA_PWM_B_V = 10011,
    RA_PWM_B_W = 10012,
};

enum RenesasSimpleFOCAdcChannel
{
    RA_ADC2_1 = ADC_CHANNEL_1,
    RA_ADC2_2 = ADC_CHANNEL_2,
    RA_ADC1_1 = ADC_CHANNEL_11,
    RA_ADC1_2 = ADC_CHANNEL_12,
    RA_ADC_U_CURRENT = RA_ADC1_2, // P014: U phase current sense on this board
    RA_ADC_V_CURRENT = RA_ADC1_1, // P013: V phase current sense on this board
};

#ifdef __cplusplus
extern "C" void simplefoc_app_main(void);
extern "C" bool renesas_simplefoc_set_phase_order(uint8_t order);
extern "C" uint8_t renesas_simplefoc_get_phase_order(void);
extern "C" uint32_t renesas_serial_tx_dropped_bytes(void);
extern "C" uint32_t renesas_serial_tx_start_errors(void);
extern "C" volatile uint32_t g_ra4m2_uart_tx_dropped_bytes;
extern "C" volatile uint32_t g_ra4m2_uart_tx_start_errors;
#endif
